"""empty message

Revision ID: 2ea1435dcde1
Revises: b6808ce8c9d7
Create Date: 2023-11-04 18:07:03.998275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea1435dcde1'
down_revision = 'b6808ce8c9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_watched_movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watched_movies',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('movie_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='fk_user_watched_movies_movie_id_movies'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_watched_movies_user_id_users')
    )
    # ### end Alembic commands ###
