"""message

Revision ID: 4b425804965e
Revises: 58f743e18c8f
Create Date: 2023-10-24 21:05:51.152492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b425804965e'
down_revision = '58f743e18c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_ratings_movie_id_movies'), 'movies', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ratings_movie_id_movies'), type_='foreignkey')

    # ### end Alembic commands ###
