"""message

Revision ID: 509acb3b1116
Revises: 
Create Date: 2023-10-24 20:41:55.276078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509acb3b1116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_user_movie_association_movie_id_movies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_movie_association_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie_association')
    # ### end Alembic commands ###
