"""empty message

Revision ID: 704cb9a58414
Revises: c3de1fa0f861
Create Date: 2023-11-04 17:12:55.422864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704cb9a58414'
down_revision = 'c3de1fa0f861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie_association',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('movie_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='fk_user_movie_association_movie_id_movies'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_movie_association_user_id_users')
    )
    # ### end Alembic commands ###
