"""message

Revision ID: c1d404f28f5e
Revises: 4b425804965e
Create Date: 2023-10-24 21:10:26.377745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d404f28f5e'
down_revision = '4b425804965e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lists_movie_id_movies'), 'movies', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lists_movie_id_movies'), type_='foreignkey')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
